name: "helloworld"

on:
  push:
    branches:
      - master
      - production

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: "print hello world"
        run: echo "Inside master branch created the helo.yml"

