name: "Multiple_event"

on:
  push:
    branches:
      - master
      - production
      - test
  pull_request:
    branches:
      - test
  workflow_dispatch:

jobs:
  on_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "print hello world"
        run: echo "Patil"

  on_pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "Pull request is run"
        run: echo "Done"

  on_workflow_dispatch:
    if: github.event_name== 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "this is workflow dispatch"
        run: echo "workflow dispatch"

